# File: azure-pipelines.yml
name: $(Build.BuildId)

variables:
  - template: buildVars.yml@templates
  - name: mainProject
    value: Refactorius.Common

resources:
  repositories:
    - repository: templates
      type: git
      name: Refactorius.Common/Templates

trigger: none

stages:
  - template: buildStage-lib20-v1.yml@templates
  - template: publishLocalStage-pkg-v1.yml@templates
  - template: continueIfMasterStage-v1.yml@templates
  - template: publishNugetStage-pkg-v1.yml@templates