# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildConfiguration: 'Debug'
  VersionSuffix: $[counter('versioncounter', 100)]
  home: Refactorius.Common
  main: $(home)/Refactorius.Common

name: $(VersionSuffix)

trigger: none

steps:

- script: type azure-pipelines.yml
  name: show
  displayName: 'Show yaml source in $(Build.SourceBranch)'
  
- task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
  displayName: 'Unset VersionSuffix if Master branch'
  condition: eq(variables['Build.SourceBranch'], 'Master')
  inputs:
    VariableName: VersionSuffix
    Value: ''

- task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
  displayName: 'Set buildConfiguration to Release if Master branch'
  condition: eq(variables['Build.SourceBranch'], 'Master')
  inputs:
    VariableName: BuildConfiguration
    Value: 'Release'

- script: dotnet restore $(main).sln --configfile nuget.config
  name: restore
  displayName: 'Restore packages'

- script: dotnet build $(main).sln --no-restore -c $(BuildConfiguration) /p:VersionSuffix=$(VersionSuffix
  displayName: 'Build all projects as $(BuildConfiguration) with version suffix $(VersionSuffix)'

- task: DotNetCoreCLI@2
  name: test
  displayName: 'Run tests'
  inputs:
    command: test
    projects: $(home)/**/*Test*.csproj
    nobuild: true
    publishTestResults: true

- script: |
    dotnet pack $(main)/Refactorius.Common.csproj --no-build --no-restore -c "$(BuildConfiguration)" -o "$(Build.ArtifactStagingDirectory)"
  name: pack
  displayName: 'Pack library'

- task: DotNetCoreCLI@2
  name: push
  displayName: 'Push library'
  inputs:
    command: push
    nuGetFeedType: internal
    packagesToPush: $(build.artifactStagingDirectory)/*.nupkg
    publishVstsFeed: RefactoriusPackages

- script: dotnet test $(home)/$(home).Tests.Net471/$(home).Tests.Net471.csproj --no-build --no-restore
  name: test_Net471
  displayName: 'Run tests on Net471'

- script: dotnet test $(home)/$(home).Tests.NetCore20/$(home).Tests.NetCore20.csproj --no-build --no-restore
  name: test_NetCore20
  displayName: 'Run tests on NetCore20'

