# File: azure-pipelines.yml
name: $(Build.BuildId)

variables:
  - template: buildVars.yml@templates
  - name: mainProject
    value: Refactorius.Common

resources:
  repositories:
    - repository: templates
      type: git
      name: Refactorius.Common/Templates

trigger: none

stages:
  - template: allBuildStages-lib20-v1.yml@templates
